version: "3"
services:
  web:
    build:
      context: .
      dockerfile: NodeJS
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./node/app:/usr/src/app/app
    depends_on:
      - db
  db:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
volumes:
  data-volume: